In [1]:
import pandas as pd
import psycopg2
import os

In [2]:
conn = psycopg2.connect(database="beta-prod-idms-db",
                                user="postgres",
                                password="Netradyne123", host ="pg-testing.netradyne.info", port = "5432")

In [3]:
conn

In [4]:
query = "select vh.tenant_id, tn.tenant_unique_name, vh.chasis_number, vh.registration_number, vh.nickname, vh.is_encrypted,vh.vehicle_id from ndvehiclemaster vh, ndtenantmaster tn where vh.tenant_id=tn.tenant_id and  vh.is_placeholder_vehicle=1"
vehicles = pd.read_sql_query(query,conn)
query = "select vh.vehicle_id, dv.manufacturer_device_id from ndvehicledeviceconfigurations vh, nddevicemaster dv where vh.device_id =dv.manufacturer_device_id_seq union select vh.vehicle_id, dv.manufacturer_device_id from ndvehicledeviceconfigurations_archive vh, nddevicemaster dv where vh.device_id =dv.manufacturer_device_id_seq"
mapping = pd.read_sql_query(query,conn)

In [5]:
vehicles.head(100)

,tenant_id,tenant_unique_name,chasis_number,registration_number,nickname,is_encrypted,vehicle_id
0,1064.0,HALVOR_LINES,V_16302837_HALVOR_LINES,V_16302837_HALVOR_LINES,V_16302837_HALVOR_LINES,0,5217.0
1,1064.0,HALVOR_LINES,V_16302838_HALVOR_LINES,V_16302838_HALVOR_LINES,V_16302838_HALVOR_LINES,0,5218.0
2,1064.0,HALVOR_LINES,V_16302842_HALVOR_LINES,V_16302842_HALVOR_LINES,V_16302842_HALVOR_LINES,0,5220.0
3,1064.0,HALVOR_LINES,V_16302843_HALVOR_LINES,V_16302843_HALVOR_LINES,V_16302843_HALVOR_LINES,0,5221.0
4,1027.0,INSTALLCHECKACCOUNT,chasis92117,registration92117,nickname92117,0,92117.0
...,...,...,...,...,...,...,...
95,2366.0,573936211540289,V_16319025_573936211540289,V_16319025_573936211540289,V_16319025_573936211540289,0,70006.0
96,2366.0,573936211540289,V_16319436_573936211540289,V_16319436_573936211540289,V_16319436_573936211540289,0,70007.0
97,2366.0,573936211540289,V_16319422_573936211540289,V_16319422_573936211540289,V_16319422_573936211540289,0,70008.0
98,2366.0,573936211540289,V_16319527_573936211540289,V_16319527_573936211540289,V_16319527_573936211540289,0,70009.0
99,1033.0,HMD,V_16303046_HMD,V_16303046_HMD,V_16303046_HMD,0,5559.0

In [6]:
vehicles.shape

(75446, 7)

In [7]:
mapping.head()

   vehicle_id manufacturer_device_id
0         2.0             NDTEST1-BG
1         5.0             NDTEST2-BG
2         6.0                NDDAVID
3         7.0              NDPRAVEEN
4         8.0              NDKEVIN_2

In [8]:
vehicles = pd.merge(vehicles, mapping, how ='inner', on ='vehicle_id')

In [9]:
vehicles.loc[~(vehicles["tenant_id"]==1027.0),["chasis_number","registration_number","nickname"]] = "V_" + vehicles["manufacturer_device_id"] + "_" + vehicles["tenant_unique_name"]

In [10]:
vehicles.loc[vehicles["tenant_id"]==1027.0,["registration_number","nickname"]] = vehicles["manufacturer_device_id"]
vehicles.loc[vehicles["tenant_id"]==1027.0,["chasis_number"]] = "VIN_" + vehicles["manufacturer_device_id"]

In [11]:
vehicles["is_encrypted"] = 0

In [12]:
vehicles

,tenant_id,tenant_unique_name,chasis_number,registration_number,nickname,is_encrypted,vehicle_id,manufacturer_device_id
0,1064.0,HALVOR_LINES,V_16302837_HALVOR_LINES,V_16302837_HALVOR_LINES,V_16302837_HALVOR_LINES,0,5217.0,16302837
1,1064.0,HALVOR_LINES,V_16302838_HALVOR_LINES,V_16302838_HALVOR_LINES,V_16302838_HALVOR_LINES,0,5218.0,16302838
2,1064.0,HALVOR_LINES,V_16302842_HALVOR_LINES,V_16302842_HALVOR_LINES,V_16302842_HALVOR_LINES,0,5220.0,16302842
3,1064.0,HALVOR_LINES,V_16302843_HALVOR_LINES,V_16302843_HALVOR_LINES,V_16302843_HALVOR_LINES,0,5221.0,16302843
4,1027.0,INSTALLCHECKACCOUNT,VIN_16328618,16328618,16328618,0,92117.0,16328618
...,...,...,...,...,...,...,...,...
71302,1064.0,HALVOR_LINES,V_16302811_HALVOR_LINES,V_16302811_HALVOR_LINES,V_16302811_HALVOR_LINES,0,5210.0,16302811
71303,1064.0,HALVOR_LINES,V_16302816_HALVOR_LINES,V_16302816_HALVOR_LINES,V_16302816_HALVOR_LINES,0,5211.0,16302816
71304,1064.0,HALVOR_LINES,V_16302821_HALVOR_LINES,V_16302821_HALVOR_LINES,V_16302821_HALVOR_LINES,0,5212.0,16302821
71305,1064.0,HALVOR_LINES,V_16302822_HALVOR_LINES,V_16302822_HALVOR_LINES,V_16302822_HALVOR_LINES,0,5213.0,16302822
71306,1064.0,HALVOR_LINES,V_16302825_HALVOR_LINES,V_16302825_HALVOR_LINES,V_16302825_HALVOR_LINES,0,5214.0,16302825

In [13]:
path=os.getcwd()+'/placeholdervehicles.csv'
place_list=pd.read_csv(path)

In [14]:
place_list

,engine_number,chasis_number,registration_number,nickname,is_encrypted,vehicle_id
0,NaN,V_16318207_651821881539295,V_16318207_651821881539295,V_16318207_651821881539295,0,65156
1,NaN,V_16311734_GPS_INSIGHT,V_16311734_GPS_INSIGHT,V_16311734_GPS_INSIGHT,0,43194
2,NaN,V_16311735_GPS_INSIGHT,V_16311735_GPS_INSIGHT,V_16311735_GPS_INSIGHT,0,43195
3,NaN,V_16311736_GPS_INSIGHT,V_16311736_GPS_INSIGHT,V_16311736_GPS_INSIGHT,0,43196
4,NaN,V_16311743_GPS_INSIGHT,V_16311743_GPS_INSIGHT,V_16311743_GPS_INSIGHT,0,43197
...,...,...,...,...,...,...
3978,NaN,1FUJA6CK25DV40203,1L45839,723,0,39846
3979,NaN,1XP5DB9X85D842038,1M16729,1096,0,39884
3980,NaN,1XKAB9X26J117431,1M80367,1299,0,39957
3981,NaN,1FUJGLDV7DSBY1868,1L08826,1522,0,39976
3982,NaN,4V4NC9EJXBN530697,R395292,1554,0,40000

In [15]:
vehicles = pd.concat([vehicles, place_list])

In [16]:
vehicles

,tenant_id,tenant_unique_name,chasis_number,registration_number,nickname,is_encrypted,vehicle_id,manufacturer_device_id,engine_number
0,1064.0,HALVOR_LINES,V_16302837_HALVOR_LINES,V_16302837_HALVOR_LINES,V_16302837_HALVOR_LINES,0,5217.0,16302837,NaN
1,1064.0,HALVOR_LINES,V_16302838_HALVOR_LINES,V_16302838_HALVOR_LINES,V_16302838_HALVOR_LINES,0,5218.0,16302838,NaN
2,1064.0,HALVOR_LINES,V_16302842_HALVOR_LINES,V_16302842_HALVOR_LINES,V_16302842_HALVOR_LINES,0,5220.0,16302842,NaN
3,1064.0,HALVOR_LINES,V_16302843_HALVOR_LINES,V_16302843_HALVOR_LINES,V_16302843_HALVOR_LINES,0,5221.0,16302843,NaN
4,1027.0,INSTALLCHECKACCOUNT,VIN_16328618,16328618,16328618,0,92117.0,16328618,NaN
...,...,...,...,...,...,...,...,...,...
3978,NaN,NaN,1FUJA6CK25DV40203,1L45839,723,0,39846.0,NaN,NaN
3979,NaN,NaN,1XP5DB9X85D842038,1M16729,1096,0,39884.0,NaN,NaN
3980,NaN,NaN,1XKAB9X26J117431,1M80367,1299,0,39957.0,NaN,NaN
3981,NaN,NaN,1FUJGLDV7DSBY1868,1L08826,1522,0,39976.0,NaN,NaN
3982,NaN,NaN,4V4NC9EJXBN530697,R395292,1554,0,40000.0,NaN,NaN

In [17]:
vehicles = vehicles.drop(["tenant_id","tenant_unique_name","manufacturer_device_id","engine_number"],axis=1)

In [18]:
vehicles=vehicles.sort_values(by="vehicle_id")

In [19]:
vehicles = vehicles.drop_duplicates(subset=['nickname'], keep='last')

In [20]:
vehicles["vehicle_id"] = vehicles["vehicle_id"].astype(int)

In [21]:
vehicles

,chasis_number,registration_number,nickname,is_encrypted,vehicle_id
2638,v16300077,v16300077,v16300077,0,225
2632,v16300117,v16300117,v16300117,0,240
3001,VIN_16300155,16300155,16300155,0,394
21453,VIN_16300167,16300167,16300167,0,395
71187,V_16300155_NETRADYNE,V_16300155_NETRADYNE,V_16300155_NETRADYNE,0,398
...,...,...,...,...,...
16384,V_16329430_N534741441570109,V_16329430_N534741441570109,V_16329430_N534741441570109,0,112707
16390,V_16331267_236953761538184,V_16331267_236953761538184,V_16331267_236953761538184,0,112710
16391,V_16330732_751415131539139,V_16330732_751415131539139,V_16330732_751415131539139,0,112711
16392,V_16303773_CONTINENTAL_EXPRESS,V_16303773_CONTINENTAL_EXPRESS,V_16303773_CONTINENTAL_EXPRESS,0,112721
16393,V_16302961_CONTINENTAL_EXPRESS,V_16302961_CONTINENTAL_EXPRESS,V_16302961_CONTINENTAL_EXPRESS,0,112722

In [22]:
vehicle_list = [tuple(row) for row in vehicles.values]

In [23]:
vehicle_list

[('v16300077', 'v16300077', 'v16300077', 0, 225),
 ('v16300117', 'v16300117', 'v16300117', 0, 240),
 ('VIN_16300155', '16300155', '16300155', 0, 394),
 ('VIN_16300167', '16300167', '16300167', 0, 395),
 ('V_16300155_NETRADYNE',
  'V_16300155_NETRADYNE',
  'V_16300155_NETRADYNE',
  0,
  398),
 ('VIN_16300188', '16300188', '16300188', 0, 405),
 ('VIN_16300189', '16300189', '16300189', 0, 406),
 ('VIN_16300198', '16300198', '16300198', 0, 407),
 ('VIN_16300192', '16300192', '16300192', 0, 408),
 ('VIN_16300190', '16300190', '16300190', 0, 409),
 ('VIN_16300224', '16300224', '16300224', 0, 410),
 ('VIN_16300208', '16300208', '16300208', 0, 411),
 ('VIN_16300205', '16300205', '16300205', 0, 412),
 ('VIN_16300221', '16300221', '16300221', 0, 413),
 ('VIN_16300212', '16300212', '16300212', 0, 414),
 ('VIN_16300177', '16300177', '16300177', 0, 415),
 ('VIN_16300220', '16300220', '16300220', 0, 416),
 ('VIN_16300215', '16300215', '16300215', 0, 417),
 ('VIN_16300225', '16300225', '16300225', 0, 418),
 ('VIN_16300199', '16300199', '16300199', 0, 419),
 ('VIN_16300191', '16300191', '16300191', 0, 420),
 ('VIN_16300213', '16300213', '16300213', 0, 421),
 ('VIN_16300176', '16300176', '16300176', 0, 422),
 ('VIN_16300174', '16300174', '16300174', 0, 423),
 ('VIN_16300186', '16300186', '16300186', 0, 424),
 ('VIN_16300187', '16300187', '16300187', 0, 425),
 ('VIN_16300172', '16300172', '16300172', 0, 426),
 ('VIN_16300206', '16300206', '16300206', 0, 427),
 ('VIN_16300183', '16300183', '16300183', 0, 428),
 ('VIN_16300182', '16300182', '16300182', 0, 429),
 ('VIN_16300178', '16300178', '16300178', 0, 430),
 ('VIN_16300211', '16300211', '16300211', 0, 431),
 ('VIN_16300217', '16300217', '16300217', 0, 432),
 ('VIN_16300204', '16300204', '16300204', 0, 433),
 ('VIN_16300219', '16300219', '16300219', 0, 434),
 ('VIN_16300203', '16300203', '16300203', 0, 435),
 ('VIN_16300202', '16300202', '16300202', 0, 436),
 ('VIN_16300223', '16300223', '16300223', 0, 437),
 ('VIN_16300193', '16300193', '16300193', 0, 438),
 ('VIN_16300201', '16300201', '16300201', 0, 439),
 ('VIN_16300233', '16300233', '16300233', 0, 440),
 ('VIN_16300209', '16300209', '16300209', 0, 441),
 ('VIN_16300200', '16300200', '16300200', 0, 442),
 ('VIN_16300218', '16300218', '16300218', 0, 443),
 ('VIN_16300216', '16300216', '16300216', 0, 444),
 ('VIN_16300184', '16300184', '16300184', 0, 445),
 ('VIN_16300171', '16300171', '16300171', 0, 446),
 ('VIN_16300207', '16300207', '16300207', 0, 447),
 ('VIN_16300194', '16300194', '16300194', 0, 448),
 ('VIN_16300196', '16300196', '16300196', 0, 449),
 ('VIN_16300179', '16300179', '16300179', 0, 450),
 ('VIN_16300175', '16300175', '16300175', 0, 451),
 ('VIN_16300173', '16300173', '16300173', 0, 452),
 ('VIN_16300181', '16300181', '16300181', 0, 453),
 ('VIN_16300185', '16300185', '16300185', 0, 454),
 ('VIN_16300329', '16300329', '16300329', 0, 455),
 ('VIN_16300355', '16300355', '16300355', 0, 456),
 ('VIN_16300358', '16300358', '16300358', 0, 457),
 ('VIN_16300346', '16300346', '16300346', 0, 458),
 ('VIN_16300301', '16300301', '16300301', 0, 459),
 ('VIN_16300340', '16300340', '16300340', 0, 460),
 ('VIN_16300357', '16300357', '16300357', 0, 461),
 ('VIN_16300343', '16300343', '16300343', 0, 462),
 ('VIN_16300351', '16300351', '16300351', 0, 463),
 ('VIN_16300263', '16300263', '16300263', 0, 464),
 ('VIN_16300260', '16300260', '16300260', 0, 465),
 ('VIN_16300295', '16300295', '16300295', 0, 466),
 ('VIN_16300322', '16300322', '16300322', 0, 467),
 ('VIN_16300303', '16300303', '16300303', 0, 468),
 ('VIN_16300300', '16300300', '16300300', 0, 469),
 ('VIN_16300302', '16300302', '16300302', 0, 470),
 ('VIN_16300305', '16300305', '16300305', 0, 471),
 ('VIN_16300298', '16300298', '16300298', 0, 472),
 ('VIN_16300290', '16300290', '16300290', 0, 473),
 ('VIN_16300304', '16300304', '16300304', 0, 474),
 ('VIN_16300291', '16300291', '16300291', 0, 475),
 ('VIN_16300333', '16300333', '16300333', 0, 476),
 ('VIN_16300332', '16300332', '16300332', 0, 477),
 ('VIN_16300330', '16300330', '16300330', 0, 478),
 ('VIN_16300320', '16300320', '16300320', 0, 479),
 ('VIN_16300328', '16300328', '16300328', 0, 480),
 ('VIN_16300324', '16300324', '16300324', 0, 481),
 ('VIN_16300296', '16300296', '16300296', 0, 482),
 ('VIN_16300327', '16300327', '16300327', 0, 483),
 ('VIN_16300321', '16300321', '16300321', 0, 484),
 ('VIN_16300331', '16300331', '16300331', 0, 485),
 ('VIN_16300325', '16300325', '16300325', 0, 486),
 ('VIN_16300354', '16300354', '16300354', 0, 487),
 ('VIN_16300323', '16300323', '16300323', 0, 488),
 ('VIN_16300268', '16300268', '16300268', 0, 489),
 ('VIN_16300214', '16300214', '16300214', 0, 490),
 ('VIN_16300261', '16300261', '16300261', 0, 491),
 ('VIN_16300210', '16300210', '16300210', 0, 492),
 ('VIN_16300238', '16300238', '16300238', 0, 493),
 ('VIN_16300197', '16300197', '16300197', 0, 494),
 ('VIN_16300235', '16300235', '16300235', 0, 495),
 ('VIN_16300259', '16300259', '16300259', 0, 496),
 ('VIN_16300236', '16300236', '16300236', 0, 497),
 ('VIN_16300237', '16300237', '16300237', 0, 498),
 ('VIN_16300232', '16300232', '16300232', 0, 499),
 ('VIN_16300269', '16300269', '16300269', 0, 500),
 ('VIN_16300240', '16300240', '16300240', 0, 501),
 ('VIN_16300239', '16300239', '16300239', 0, 502),
 ('VIN_16300258', '16300258', '16300258', 0, 503),
 ('VIN_16300222', '16300222', '16300222', 0, 504),
 ('VIN_16300262', '16300262', '16300262', 0, 506),
 ('VIN_16300352', '16300352', '16300352', 0, 507),
 ('VIN_16300339', '16300339', '16300339', 0, 508),
 ('VIN_16300297', '16300297', '16300297', 0, 509),
 ('VIN_16300348', '16300348', '16300348', 0, 510),
 ('VIN_16300356', '16300356', '16300356', 0, 511),
 ('VIN_16300275', '16300275', '16300275', 0, 512),
 ('VIN_16300360', '16300360', '16300360', 0, 513),
 ('VIN_16300349', '16300349', '16300349', 0, 514),
 ('VIN_16300338', '16300338', '16300338', 0, 515),
 ('VIN_16300273', '16300273', '16300273', 0, 516),
 ('VIN_16300345', '16300345', '16300345', 0, 517),
 ('VIN_16300359', '16300359', '16300359', 0, 518),
 ('VIN_16300336', '16300336', '16300336', 0, 519),
 ('VIN_16300326', '16300326', '16300326', 0, 520),
 ('VIN_16300293', '16300293', '16300293', 0, 521),
 ('VIN_16300353', '16300353', '16300353', 0, 522),
 ('V_16300262_NETRADYNE',
  'V_16300262_NETRADYNE',
  'V_16300262_NETRADYNE',
  0,
  523),
 ('V_16300359_NETRADYNE',
  'V_16300359_NETRADYNE',
  'V_16300359_NETRADYNE',
  0,
  524),
 ('VIN_16300227', '16300227', '16300227', 0, 552),
 ('VIN_16300288', '16300288', '16300288', 0, 553),
 ('VIN_16300398', '16300398', '16300398', 0, 554),
 ('VIN_16300413', '16300413', '16300413', 0, 555),
 ('VIN_16300380', '16300380', '16300380', 0, 556),
 ('VIN_16300277', '16300277', '16300277', 0, 557),
 ('VIN_16300404', '16300404', '16300404', 0, 558),
 ('VIN_16300311', '16300311', '16300311', 0, 559),
 ('VIN_16300369', '16300369', '16300369', 0, 560),
 ('VIN_16300245', '16300245', '16300245', 0, 561),
 ('VIN_16300276', '16300276', '16300276', 0, 564),
 ('VIN_16300278', '16300278', '16300278', 0, 565),
 ('VIN_16300270', '16300270', '16300270', 0, 566),
 ('VIN_16300180', '16300180', '16300180', 0, 567),
 ('VIN_16300266', '16300266', '16300266', 0, 568),
 ('VIN_16300279', '16300279', '16300279', 0, 569),
 ('VIN_16300282', '16300282', '16300282', 0, 570),
 ('VIN_16300335', '16300335', '16300335', 0, 571),
 ('VIN_16300334', '16300334', '16300334', 0, 572),
 ('VIN_16300267', '16300267', '16300267', 0, 573),
 ('VIN_16300341', '16300341', '16300341', 0, 574),
 ('VIN_16300289', '16300289', '16300289', 0, 575),
 ('VIN_16300362', '16300362', '16300362', 0, 577),
 ('VIN_16300299', '16300299', '16300299', 0, 578),
 ('VIN_16300310', '16300310', '16300310', 0, 579),
 ('VIN_16300272', '16300272', '16300272', 0, 580),
 ('VIN_16300281', '16300281', '16300281', 0, 581),
 ('VIN_16300287', '16300287', '16300287', 0, 582),
 ('VIN_16300280', '16300280', '16300280', 0, 583),
 ('VIN_16300366', '16300366', '16300366', 0, 584),
 ('VIN_16300229', '16300229', '16300229', 0, 585),
 ('VIN_16300347', '16300347', '16300347', 0, 586),
 ('VIN_16300284', '16300284', '16300284', 0, 587),
 ('VIN_16300318', '16300318', '16300318', 0, 588),
 ('VIN_16300317', '16300317', '16300317', 0, 589),
 ('VIN_16300319', '16300319', '16300319', 0, 590),
 ('VIN_16300314', '16300314', '16300314', 0, 591),
 ('VIN_16300292', '16300292', '16300292', 0, 592),
 ('VIN_16300253', '16300253', '16300253', 0, 593),
 ('16300249', '16300249', '16300249', 0, 594),
 ('VIN_16300257', '16300257', '16300257', 0, 595),
 ('VIN_16300231', '16300231', '16300231', 0, 596),
 ('V_16300348_NETRADYNE',
  'V_16300348_NETRADYNE',
  'V_16300348_NETRADYNE',
  0,
  600),
 ('VIN_16300372', '16300372', '16300372', 0, 605),
 ('VIN_16300374', '16300374', '16300374', 0, 606),
 ('VIN_16300381', '16300381', '16300381', 0, 607),
 ('VIN_16300388', '16300388', '16300388', 0, 608),
 ('VIN_16300254', '16300254', '16300254', 0, 609),
 ('VIN_16300228', '16300228', '16300228', 0, 661),
 ('VIN_16300230', '16300230', '16300230', 0, 662),
 ('VIN_16300234', '16300234', '16300234', 0, 663),
 ('VIN_16300243', '16300243', '16300243', 0, 664),
 ('VIN_16300246', '16300246', '16300246', 0, 665),
 ('VIN_16300250', '16300250', '16300250', 0, 666),
 ('VIN_16300252', '16300252', '16300252', 0, 667),
 ('VIN_16300274', '16300274', '16300274', 0, 668),
 ('VIN_16300294', '16300294', '16300294', 0, 669),
 ('VIN_16300308', '16300308', '16300308', 0, 670),
 ('VIN_16300312', '16300312', '16300312', 0, 671),
 ('VIN_16300342', '16300342', '16300342', 0, 672),
 ('VIN_16300350', '16300350', '16300350', 0, 673),
 ('VIN_16300361', '16300361', '16300361', 0, 674),
 ('VIN_16300363', '16300363', '16300363', 0, 675),
 ('VIN_16300370', '16300370', '16300370', 0, 676),
 ('VIN_16300371', '16300371', '16300371', 0, 677),
 ('VIN_16300373', '16300373', '16300373', 0, 678),
 ('VIN_16300376', '16300376', '16300376', 0, 679),
 ('VIN_16300379', '16300379', '16300379', 0, 680),
 ('VIN_16300382', '16300382', '16300382', 0, 681),
 ('VIN_16300383', '16300383', '16300383', 0, 682),
 ('VIN_16300384', '16300384', '16300384', 0, 683),
 ('VIN_16300385', '16300385', '16300385', 0, 684),
 ('VIN_16300386', '16300386', '16300386', 0, 685),
 ('VIN_16300387', '16300387', '16300387', 0, 686),
 ('VIN_16300389', '16300389', '16300389', 0, 687),
 ('VIN_16300390', '16300390', '16300390', 0, 688),
 ('VIN_16300392', '16300392', '16300392', 0, 689),
 ('VIN_16300393', '16300393', '16300393', 0, 690),
 ('VIN_16300394', '16300394', '16300394', 0, 691),
 ('VIN_16300395', '16300395', '16300395', 0, 692),
 ('VIN_16300396', '16300396', '16300396', 0, 693),
 ('VIN_16300397', '16300397', '16300397', 0, 694),
 ('VIN_16300399', '16300399', '16300399', 0, 695),
 ('VIN_16300400', '16300400', '16300400', 0, 696),
 ('VIN_16300401', '16300401', '16300401', 0, 697),
 ('VIN_16300402', '16300402', '16300402', 0, 698),
 ('VIN_16300405', '16300405', '16300405', 0, 699),
 ('VIN_16300406', '16300406', '16300406', 0, 700),
 ('VIN_16300407', '16300407', '16300407', 0, 701),
 ('VIN_16300408', '16300408', '16300408', 0, 702),
 ('VIN_16300409', '16300409', '16300409', 0, 703),
 ('VIN_16300410', '16300410', '16300410', 0, 704),
 ('VIN_16300411', '16300411', '16300411', 0, 705),
 ('VIN_16300412', '16300412', '16300412', 0, 706),
 ('VIN_lp16300226', 'lp16300226', 'vn16300226', 0, 707),
 ('VIN_16300316', '16300316', '16300316', 0, 718),
 ('VIN_16300309', '16300309', '16300309', 0, 719),
 ('VIN_16300307', '16300307', '16300307', 0, 720),
 ('VIN_16300248', '16300248', '16300248', 0, 721),
 ('VIN_16300241', '16300241', '16300241', 0, 722),
 ('VIN_16300256', '16300256', '16300256', 0, 723),
 ('VIN_16300255', '16300255', '16300255', 0, 724),
 ('VIN_16300344', '16300344', '16300344', 0, 725),
 ('VIN_16300283', '16300283', '16300283', 0, 726),
 ('VIN_16300286', '16300286', '16300286', 0, 727),
 ('VIN_16300306', '16300306', '16300306', 0, 728),
 ('VIN_16300271', '16300271', '16300271', 0, 729),
 ('VIN_16300367', '16300367', '16300367', 0, 730),
 ('VIN_16300368', '16300368', '16300368', 0, 731),
 ('VIN_16300313', '16300313', '16300313', 0, 732),
 ('VIN_16300247', '16300247', '16300247', 0, 733),
 ('VIN_16300124', '16300124', '16300124', 0, 751),
 ('VIN_16300067', '16300067', '16300067', 0, 752),
 ('VIN_16300023', '16300023', '16300023', 0, 753),
 ('VIN_16300025', '16300025', '16300025', 0, 754),
 ('VIN_16300028', '16300028', '16300028', 0, 755),
 ('VIN_16300030', '16300030', '16300030', 0, 756),
 ('VIN_16300031', '16300031', '16300031', 0, 757),
 ('VIN_16300037', '16300037', '16300037', 0, 758),
 ('VIN_16300038', '16300038', '16300038', 0, 759),
 ('VIN_16300042', '16300042', '16300042', 0, 760),
 ('VIN_16300049', '16300049', '16300049', 0, 761),
 ('VIN_16300051', '16300051', '16300051', 0, 762),
 ('VIN_16300058', '16300058', '16300058', 0, 763),
 ('VIN_16300063', '16300063', '16300063', 0, 764),
 ('VIN_16300069', '16300069', '16300069', 0, 765),
 ('VIN_16300071', '16300071', '16300071', 0, 766),
 ('VIN_16300073', '16300073', '16300073', 0, 767),
 ('VIN_16300074', '16300074', '16300074', 0, 768),
 ('VIN_16300076', '16300076', '16300076', 0, 769),
 ('VIN_16300079', '16300079', '16300079', 0, 770),
 ('VIN_16300080', '16300080', '16300080', 0, 771),
 ('VIN_16300082', '16300082', '16300082', 0, 772),
 ('VIN_16300085', '16300085', '16300085', 0, 773),
 ('VIN_16300089', '16300089', '16300089', 0, 774),
 ('VIN_16300092', '16300092', '16300092', 0, 775),
 ('VIN_16300093', '16300093', '16300093', 0, 776),
 ('VIN_16300099', '16300099', '16300099', 0, 777),
 ('VIN_16300135', '16300135', '16300135', 0, 778),
 ('VIN_16300147', '16300147', '16300147', 0, 779),
 ('VIN_16300157', '16300157', '16300157', 0, 780),
 ('VIN_16300012', '16300012', '16300012', 0, 781),
 ('16300034', '16300034', '16300034', 0, 782),
 ('VIN_16300040', '16300040', '16300040', 0, 783),
 ('VIN_16300045', '16300045', '16300045', 0, 784),
 ('VIN_16300047', '16300047', '16300047', 0, 785),
 ('VIN_16300050', '16300050', '16300050', 0, 786),
 ('VIN_16300053', '16300053', '16300053', 0, 787),
 ('VIN_16300057', '16300057', '16300057', 0, 788),
 ('VIN_16300059', '16300059', '16300059', 0, 789),
 ('VIN_16300061', '16300061', '16300061', 0, 790),
 ('VIN_16300065', '16300065', '16300065', 0, 791),
 ('VIN_16300066', '16300066', '16300066', 0, 792),
 ('VIN_16300068', '16300068', '16300068', 0, 793),
 ('VIN_16300072', '16300072', '16300072', 0, 794),
 ('VIN_16300106', '16300106', '16300106', 0, 795),
 ('16300119', '16300119', '16300119', 0, 796),
 ('VIN_16300126', '16300126', '16300126', 0, 797),
 ('VIN_16300150', '16300150', '16300150', 0, 798),
 ('VIN_16300152', '16300152', '16300152', 0, 799),
 ('16300158', '16300158', '16300158', 0, 800),
 ('VIN_16300226', '16300226', '16300226', 0, 801),
 ('VIN_16300403', '16300403', '16300403', 0, 811),
 ('VIN_16300375', '16300375', '16300375', 0, 812),
 ('VIN_16300377', '16300377', '16300377', 0, 813),
 ('VIN_16300451', '16300451', '16300451', 0, 814),
 ('VIN_16300457', '16300457', '16300457', 0, 815),
 ('VIN_16300432', '16300432', '16300432', 0, 816),
 ('VIN_16300418', '16300418', '16300418', 0, 817),
 ('VIN_16300433', '16300433', '16300433', 0, 818),
 ('VIN_16300365', '16300365', '16300365', 0, 819),
 ('VIN_16300337', '16300337', '16300337', 0, 820),
 ('VIN_16300378', '16300378', '16300378', 0, 821),
 ('VIN_16300425', '16300425', '16300425', 0, 822),
 ('VIN_16300444', '16300444', '16300444', 0, 823),
 ('VIN_16300448', '16300448', '16300448', 0, 824),
 ('VIN_16300434', '16300434', '16300434', 0, 825),
 ('VIN_16300414', '16300414', '16300414', 0, 826),
 ('VIN_16300423', '16300423', '16300423', 0, 827),
 ('VIN_16300421', '16300421', '16300421', 0, 828),
 ('VIN_16300456', '16300456', '16300456', 0, 829),
 ('VIN_16300424', '16300424', '16300424', 0, 830),
 ('VIN_16300496', '16300496', '16300496', 0, 831),
 ('VIN_16300435', '16300435', '16300435', 0, 832),
 ('VIN_16300497', '16300497', '16300497', 0, 833),
 ('VIN_16300445', '16300445', '16300445', 0, 834),
 ('VIN_16300440', '16300440', '16300440', 0, 835),
 ('VIN_16300428', '16300428', '16300428', 0, 836),
 ('VIN_16300459', '16300459', '16300459', 0, 837),
 ('VIN_16300422', '16300422', '16300422', 0, 838),
 ('VIN_16300419', '16300419', '16300419', 0, 839),
 ('VIN_16300495', '16300495', '16300495', 0, 840),
 ('VIN_16300438', '16300438', '16300438', 0, 863),
 ('VIN_16300491', '16300491', '16300491', 0, 870),
 ('VIN_16300447', '16300447', '16300447', 0, 871),
 ('VIN_16300446', '16300446', '16300446', 0, 872),
 ('VIN_16300687', '16300687', '16300687', 0, 873),
 ('VIN_16300713', '16300713', '16300713', 0, 874),
 ('VIN_16300714', '16300714', '16300714', 0, 875),
 ('VIN_16300665', '16300665', '16300665', 0, 876),
 ('VIN_16300473', '16300473', '16300473', 0, 877),
 ('VIN_16300570', '16300570', '16300570', 0, 878),
 ('VIN_16300727', '16300727', '16300727', 0, 879),
 ('VIN_16300719', '16300719', '16300719', 0, 880),
 ('VIN_16300702', '16300702', '16300702', 0, 881),
 ('VIN_16300725', '16300725', '16300725', 0, 882),
 ('VIN_16300698', '16300698', '16300698', 0, 883),
 ('VIN_16300696', '16300696', '16300696', 0, 884),
 ('VIN_16300694', '16300694', '16300694', 0, 885),
 ('VIN_16300517', '16300517', '16300517', 0, 886),
 ('VIN_16300700', '16300700', '16300700', 0, 887),
 ('VIN_16300697', '16300697', '16300697', 0, 888),
 ('VIN_16300707', '16300707', '16300707', 0, 889),
 ('VIN_16300691', '16300691', '16300691', 0, 890),
 ('VIN_16300717', '16300717', '16300717', 0, 891),
 ('VIN_16300563', '16300563', '16300563', 0, 892),
 ('VIN_16300535', '16300535', '16300535', 0, 893),
 ('VIN_16300591', '16300591', '16300591', 0, 894),
 ('VIN_16300416', '16300416', '16300416', 0, 895),
 ('VIN_16300454', '16300454', '16300454', 0, 896),
 ('VIN_16300509', '16300509', '16300509', 0, 897),
 ('VIN_16300492', '16300492', '16300492', 0, 898),
 ('VIN_16300556', '16300556', '16300556', 0, 899),
 ('VIN_16300597', '16300597', '16300597', 0, 900),
 ('VIN_16300599', '16300599', '16300599', 0, 901),
 ('VIN_16300611', '16300611', '16300611', 0, 902),
 ('VIN_16300464', '16300464', '16300464', 0, 903),
 ('VIN_16300595', '16300595', '16300595', 0, 904),
 ('VIN_16300081', '16300081', '16300081', 0, 908),
 ('VIN_16300244', '16300244', '16300244', 0, 913),
 ('VIN_16300449', '16300449', '16300449', 0, 914),
 ('VIN_16300458', '16300458', '16300458', 0, 915),
 ('VIN_16300430', '16300430', '16300430', 0, 916),
 ('VIN_16300431', '16300431', '16300431', 0, 917),
 ('VIN_16300450', '16300450', '16300450', 0, 918),
 ('VIN_16300469', '16300469', '16300469', 0, 919),
 ('VIN_16300478', '16300478', '16300478', 0, 920),
 ('VIN_16300513', '16300513', '16300513', 0, 921),
 ('VIN_16300429', '16300429', '16300429', 0, 922),
 ('VIN_16300437', '16300437', '16300437', 0, 923),
 ('VIN_16300507', '16300507', '16300507', 0, 924),
 ('VIN_16300453', '16300453', '16300453', 0, 925),
 ('VIN_16300391', '16300391', '16300391', 0, 926),
 ('VIN_16300426', '16300426', '16300426', 0, 927),
 ('VIN_16300443', '16300443', '16300443', 0, 928),
 ('VIN_16300689', '16300689', '16300689', 0, 929),
 ('VIN_16300686', '16300686', '16300686', 0, 930),
 ('VIN_16300655', '16300655', '16300655', 0, 931),
 ('VIN_16300682', '16300682', '16300682', 0, 932),
 ('VIN_16300490', '16300490', '16300490', 0, 933),
 ('VIN_16300657', '16300657', '16300657', 0, 934),
 ('VIN_16300669', '16300669', '16300669', 0, 935),
 ('VIN_16300664', '16300664', '16300664', 0, 936),
 ('VIN_16300674', '16300674', '16300674', 0, 937),
 ('VIN_16300704', '16300704', '16300704', 0, 938),
 ('VIN_16300653', '16300653', '16300653', 0, 939),
 ('VIN_16300656', '16300656', '16300656', 0, 940),
 ('VIN_16300648', '16300648', '16300648', 0, 941),
 ('VIN_16300708', '16300708', '16300708', 0, 942),
 ('VIN_16300472', '16300472', '16300472', 0, 943),
 ('VIN_16300500', '16300500', '16300500', 0, 944),
 ('VIN_16300503', '16300503', '16300503', 0, 945),
 ('VIN_16300477', '16300477', '16300477', 0, 946),
 ('VIN_16300644', '16300644', '16300644', 0, 947),
 ('VIN_16300501', '16300501', '16300501', 0, 948),

In [24]:
query=  "update ndvehiclemaster set chasis_number= %s,registration_number= %s,nickname= %s,is_encrypted=%s where vehicle_id=%s"